---
abstract: 'Peek into the internals of a running POE environment'
author:
  - 'sungo <sungo@sungo.us>'
  - 'Yuval Kogman <nothingmuch@woobling.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-API-Peek
requires:
  Devel::Size: 0
  POE: 1.293
  Test::More: 0
version: 2.16
