name: POE-API-Peek
version: 1.06
author: Matt Cashner (sungo@pobox.com)
license: bsd
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.1
  POE: 0.29
  Devel::Size: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
