name: POE-API-Peek
version: 1.23
author: Matt Cashner (cpan@eekeek.org)
license: bsd
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.1
  POE: 0.2601
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
