---
abstract: 'Peek into the internals of a running POE environment'
author:
  - 'sungo <sungo@sungo.us>'
  - 'Yuval Kogman <nothingmuch@woobling.org>'
  - "Chris 'BinGOs' Williams <bingos@cpan.org>"
  - 'Philip Gwyn <gwyn@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200014, CPAN::Meta::Converter version 2.112150'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-API-Peek
requires:
  Devel::Size: 0
  POE: 1.311
  Test::More: 0
resources:
  homepage: https://github.com/bingos/poe-api-peek
  repository: https://github.com/bingos/poe-api-peek
version: 2.18
