author: Matt Cashner (sungo@pobox.com)
build_requires:
  Module::Signature: 0
  Test::Distribution: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: bsd
name: POE-API-Peek
no_index:
  directory:
    - inc
    - t
requires:
  Devel::Size: 0
  POE: 0.38
  Test::More: 0
  perl: 5.6.1
version: 1.08
