# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-API-Peek
version:      1.0465
version_from: VERSION
installdirs:  site
requires:
    POE:                           0.29
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
