---
author:
  - 'Matt Cashner (sungo@pobox.com)'
build_requires:
  Test::Distribution: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-API-Peek
no_index:
  directory:
    - inc
    - t
requires:
  Devel::Size: 0
  POE: 1.0001
  Test::More: 0
  perl: 5.006001
version: 1.32
